app/models.py
from . import db
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin
from . import login_manager


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

class User(UserMixin,db.Model):
    __tablename__ = 'users'

    id = db.Column(db.Integer,primary_key = True)
    username = db.Column(db.String(255))
    email = db.Column(db.String(255),unique = True,index = True)
    posts = db.relationship('Comment', backref = 'post', lazy = "dynamic")
    pass_secure = db.Column(db.String(255))
    comments = db.relationship('Comment', backref = '', lazy = 'dynamic' )



    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self, password):
        self.pass_secure = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.pass_secure,password)



    def __repr__(self):
        return f'User {self.username}'


class Post(db.Model):
    __tablename__ = 'posts'

    id = db.Column(db.Integer,primary_key = True)
    title = db.Column(db.String(255))
    content = db.Column(db.String())
    user_post = db.Column(db.Integer, db.ForeignKey('comments.id'))
    comments = db.relationship('Comment',backref = 'comments',lazy = "dynamic")

    def save_post(self):
        """
        Save posts 
        """
        db.session.add(self)
        db.session.commit()

    @classmethod
    def clear_posts(cls):
        Pitch.all_posts.clear()

    # display posts

    def get_posts(cat_id):
        posts = Post.query.filter_by(posts.id).all()
        return posts


    def __repr__(self):
        return f'Post {self.title}'



class Comment(db.Model):
    __tablename__ = 'comments'

    id = db.Column(db.Integer,primary_key = True)
    comment = db.Column(db.String())
    comment_title = db.Column(db.String())
    user_comment = db.Column(db.Integer, db.ForeignKey('users.id'))


    def save_comments(self):
        db.session.add(self)
        db.session.commit()

    
    @classmethod
    def get_comments(cls, id):
        comments = Comment.query.filter_by(post_id=id).all()
        return comments


    def __repr__(self):
        return f'Comment {self.comments}'

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField
from wtforms.validators import Required

class PostForm(FlaskForm):
    
    title = StringField('Post title',validators=[Required()])
    content = TextAreaField('Post content',validators=[Required()])
    submit = SubmitField('Post')

class CommentForm(FlaskForm):

    comments = TextAreaField('Leave your comment', validators=[Required()])
    submit = SubmitField(' Comment')

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from config import config_options
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_migrate import Migrate


login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'

bootstrap = Bootstrap()
db = SQLAlchemy()
migrate = Migrate()

# Initializing application
def create_app(config_name):
    app = Flask(__name__)

    # Creat the app configurations
    app.config.from_object(config_options[config_name])

    # Initializing flask extensions
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    migrate.init_app(app,db)

    # Register the blueprint
    from .main import main as main_blueprint
    from .auth import auth as auth_blueprint

    app.register_blueprint(main_blueprint)
    app.register_blueprint(auth_blueprint,url_prefix = '/auth')

    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main',__name__)

from . import views

app/main/views.py
from flask import render_template, url_for, redirect, request, flash, abort
from . import main
from .forms import PostForm, CommentForm
from ..models import User, Post, Comment
from .. import db
from flask_login import login_required

@main.route('/')
def index():

    '''
    view root page function that returns the index page and its data
    '''

    title = 'Blog'
    message = 'Blog it'

    return render_template('index.html',title = title,message = message)


@main.route('/posts/new', methods = ['GET','POST'])
@login_required
def posts():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title = form.title.data, content = form.content.data)
        db.session.add(post)
        db.session.commit()
        
        flash('Your post is create')
        return redirect(url_for('main.index'))
    return render_template('new_posts.html',post_form = form)


@main.route('/view-posts/<int:id>', methods = ['GET','POST'])
@login_required
def view_posts(id):

    posts = Post.query.get(id)

    if posts is None:
        abort(404)


    if form.validate_on_submit():
        comment = Comment.get_comments(id)

    return render_template('view_posts.html',posts = posts, comment = comment)


@main.route('/write_comment', methods=['GET','POST'])
@login_required
def post_comment():

    form = CommentForm()
    title = 'post comment'
    posts = Post.query.filter_by().first()


    return render_template('comment.html', comment_form = form, title = title)

app/templates/base.html
{% extends 'bootstrap/base.html'%}

<!-- Navbar block  --> 
{% block navbar %}
    {% include 'navbar.html' %}
{% endblock %}

app/templates/comment.html
{ % extends 'base.html' %} 
 {% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-2 col-lg-2">
            </div>

            <div class=" col-xs-12 col-sm-12 col-md-8 col-lg-8 create-group">
                {{ wtf.quick_form(comment_form) }}
            </div>

            <div class="col-md-2 col-lg-2">
            </div>

        </div>
    </div>
{% endblock %}

app/templates/index.html
{% extends 'base.html'%}
{% block styles%}
    {{ super() }}
    <link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">
{% endblock%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title> Blog it</title>
</head>
<body>
    {% block content %}
    <div class="container-fluid">

        <div class="jumbotron jumbotron-fluid">
            <div class="container">
              <h1 class="display-4"> Blog Site </h1>
              <p class="lead"> Always code as if the guy who ends up maintaining your code will be a violent psychopath who knows where you live </p>
            </div>
        </div>

            <div class="row">
                <div class="col-md-12">
                    <h3>{{message}}</h3>
                    <a class="btn btn-success btn-lg text-center" href="{{ url_for('main.posts') }}">View the posts here</a>
                    <a class="btn btn-success btn-lg text-center" href="{{ url_for('main.post_comment') }}">Post your comment</a>
                </div>
            </div>
    
    </div>
    {% endblock %}
</body>
</html>

app/templates/navbar.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <div class="navbar navbar-inverse" role="navigation">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/"> Blog </a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="/">Home</a></li>
            </div>
            <ul class="nav navbar-nav navbar-right">
              {% if current_user.is_authenticated %}
              <li style="color: white;padding: 15px;">{{current_user.username}}</li>
              <li><a href="{{url_for('auth.logout')}}"></a> Sign out</li>
              {% else %}
              <li><a href="{{url_for('auth.login')}}">Sign in</a></li>
              {%endif%}
            </ul>

        </div>
    </div>
  </body>
</html>

app/templates/new_comment.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}
 
{%block styles%}
  {{ super() }}

{%endblock%}

{% block content %}
<div class="container col-md-6" style="text-align:center">
    <h3>{{category.name|upper}} PITCH</h3>
  <div class="well">
    <hr>
    {{wtf.quick_form(comment_form)}}
 </div>
</div>
{% endblock %}

app/templates/new_posts.html
{% extends 'base.html' %}
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-md-12">
            {{wtf.quick_form(post_form)}}
        </div>
    </div>
</div>

{% endblock %}

app/templates/post_comment.html
{% extends 'base.html' %}
 {% import 'bootstrap/wtf.html' as wtf %}
  
 {%block styles%}
   {{ super() }}
{%endblock%}

{% block content %}
    <div class="container">
    {{wtf.quick_form(comment_form)}}
    </div>
{% endblock %}

app/templates/view_posts.html
{% extends 'base.html' %}
 {% import 'macros.html' as macro%}

{%block styles%}
  {{ super() }}
{%endblock%}

<!-- content block -->
{% block content %}
<div class="container">
     <div class="col-md-12">
        <p class="text-left"><a class="btn btn-info" href="{{url_for('.new_posts',id=posts)}}">Post A Pitch</a></p>
        <div class="well" style="background-color:#d0d1cb">
          <h3>{{post.content}}</h3>
        </div>

        <!-- comments -->
        <div class="col-md-6 col-offset-1">
          <table>
            <tr>
              <td><h4 class="text-left"><a class="btn btn-round" href="{{url_for('.upvote',id=pitches.id,vote_type=1)}}">Upvote <span class="glyphicon glyphicon-thumbs-up" aria-hidden="true">{{count_likes}}</span>  </a></h4></td>
              <td>&nbsp;</td>
              <td><h4 class="text-left"><a class="btn btn-round" href="{{url_for('.upvote',id=pitches.id,vote_type=2)}}">Downvote <span class="glyphicon glyphicon-thumbs-down" aria-hidden="true"></span> {{count_dislikes}} </a></h4></td>
              <td>&nbsp;</td>
              <td><h4 class="text-right">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  Comments <a class="btn btn-secondary" href="{{url_for('.post_comment',id=pitches.id)}}"> Add your comment</a></h4></td>
            </tr>
          </table>